// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd5lYm_u8f8e7-KN8jS1O4TESn9RJJf0o',
    appId: '1:292450642433:web:4bf9929fc61a1e9525ee00',
    messagingSenderId: '292450642433',
    projectId: 'shareeducation-c9e86',
    authDomain: 'shareeducation-c9e86.firebaseapp.com',
    storageBucket: 'shareeducation-c9e86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVu5BNDM9PBPFjllwA78wu0RoHLbaV6mE',
    appId: '1:292450642433:android:5163ebaccd627c9f25ee00',
    messagingSenderId: '292450642433',
    projectId: 'shareeducation-c9e86',
    storageBucket: 'shareeducation-c9e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3DdpQFiRPu07sjQPqguOBK9NkVTAqLU',
    appId: '1:292450642433:ios:71e4cfac30b0bd2625ee00',
    messagingSenderId: '292450642433',
    projectId: 'shareeducation-c9e86',
    storageBucket: 'shareeducation-c9e86.appspot.com',
    iosBundleId: 'com.example.edtechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3DdpQFiRPu07sjQPqguOBK9NkVTAqLU',
    appId: '1:292450642433:ios:71e4cfac30b0bd2625ee00',
    messagingSenderId: '292450642433',
    projectId: 'shareeducation-c9e86',
    storageBucket: 'shareeducation-c9e86.appspot.com',
    iosBundleId: 'com.example.edtechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd5lYm_u8f8e7-KN8jS1O4TESn9RJJf0o',
    appId: '1:292450642433:web:07a29c6eced217b125ee00',
    messagingSenderId: '292450642433',
    projectId: 'shareeducation-c9e86',
    authDomain: 'shareeducation-c9e86.firebaseapp.com',
    storageBucket: 'shareeducation-c9e86.appspot.com',
  );
}
